### ISSUE TITLE
Adding bootstrap styled search revisited

### ISSUE THREAD

**Issue by bryanwillis** [salcode/bootstrap-genesis#109]
This has to do with the search form [added here](https://github.com/salcode/bootstrap-genesis/issues/57)

Been meaning to get back to this for awhile, but kept forgetting about it. The 1% width  `.input-group-button` isn't getting priority over the auto width in the media query so it's not being displayed right.

**So it's looking like this:**

<img width="354" alt="screen shot 2015-10-27 at 5 48 25 pm" src="https://cloud.githubusercontent.com/assets/4042621/10774983/df0d5870-7cd2-11e5-9536-0cbc1ffbab2b.png">

**Instead of being full-width on all displays like this:**

<img width="392" alt="screen shot 2015-10-27 at 5 49 54 pm" src="https://cloud.githubusercontent.com/assets/4042621/10774975/d318309e-7cd2-11e5-804c-99a2b3533f20.png">

**There are are a lot of ways to fix this.**

**1)** Just target 768px as it seems to be only one affected:

``` css
@media (min-width: 768px) {
.search-form.form-inline .input-group > .input-group-btn {
    width: 1%;
 }
}
```

**2)** Use the sibling selector which will get priority:

``` css
input#bsg-search-form ~ .input-group-btn {
     width: 1%;
}
```

**3)** Use !important _(hacky solution)_:

``` css
.search-form .input-group-btn {
     width: 1% !important;
}
```

---

On a side note from the search bar width, we also might still need to move the glyphicon search icon down another pixel, at least the way I'm seeing it. This could possibly be retina mac display only though.

``` css
.search-form .glyphicon {
    top: 2px;
}
```

---

Alternatively, we could fix both of these issues using flexbox. While the code here is the longest it is also way cleaner than bootstraps 1% width hack.

``` css
.search-form.form-inline .input-group, 
.search-form.form-inline .input-group .input-group-btn {
    display: flex;
}
#bsg-search-form {
    flex: 1;
}
button.search-submit.btn.btn-default {
    display: inline-flex;
    padding: 0 14px;
    justify-content: center;  /* might not be needed */
    align-items: center; /*  might not be needed  */
}
@media (min-width: 768px) {
   .search-form.form-inline > .form-group {
        display: block;
    }
}
```
