### ISSUE TITLE
Adding bootstrap styled search

### ISSUE THREAD

**Issue by bryanwillis** [salcode/bootstrap-genesis#57]
This can be improved upon but I think we at least need to add the bootstrap styles to the input search field. The default search border is kinda ugly.
 
```php
add_filter( 'genesis_search_form', 'bsg_search_form', 10, 4);

function bsg_search_form( $form, $search_text, $button_text, $label ) {

    $value_or_placeholder = ( get_search_query() == '' ) ? 'placeholder' : 'value';

    $form = sprintf( '<form method="get" class="search-form form-inline" action="%s" role="search"><div class="input-group">%s<input type="search" class="search-field form-control" name="s" %s="%s" /><span class="input-group-btn"><button type="submit" class="search-submit btn btn-default" value="%s" /><i class="glyphicon glyphicon-search"></i></button></span></div></form>', home_url( '/' ), esc_html( $label ), $value_or_placeholder, esc_attr( $search_text ), esc_attr( $button_text ) );

    return $form;
}
```

Also, not sure why this is needed, but it seems to fix issues with the search width:

```css
form.search-form .input-group-btn {
    width: 1%;
}
.search-form > .input-group {
    width: 100%;
}
.search-form .glyphicon {
    top: 2px;
}
```

**Comment by bryanwillis** [comment]
![screen shot 2015-03-09 at 4 53 10 pm](https://cloud.githubusercontent.com/assets/4042621/6565265/ce3ed1de-c67c-11e4-9327-a2b95885280c.png)

**Comment by salcode** [comment]
Wow, this screenshot looks way better.  Thanks @bryanwillis 

I look forward to trying this code out and getting this added to the project

**Comment by salcode** [comment]
For future reference, here is a list of the markup changes @bryanwillis outlined above

- add class `.form-inline` to `form` element
- wrap `$search_text` in `div.input-group`
- add class `.form-control` to `input` search field
- wrap `input` button in `span.input-group-btn`
- change submit from `input` to `button`
- add classes `.search-submit` and `.btn-default` to submit `button`
- add `i.glyphicon-search` inside submit `button`

**Comment by salcode** [comment]
I found these three links helpful is building the format of the search box.

- http://getbootstrap.com/css/#forms
- http://getbootstrap.com/components/#input-groups-buttons
- http://getbootstrap.com/components/#glyphicons-examples

**Comment by bryanwillis** [comment]
Been meaning to get back to this for awhile, but kept forgetting about it. The 1% width  `.input-group-button` isn't getting priority over the auto width in the media query so it's not being displayed right.

**So it's looking like this:**

<img width="354" alt="screen shot 2015-10-27 at 5 48 25 pm" src="https://cloud.githubusercontent.com/assets/4042621/10774983/df0d5870-7cd2-11e5-9536-0cbc1ffbab2b.png">


**Instead of being full-width on all displays like this:**

<img width="392" alt="screen shot 2015-10-27 at 5 49 54 pm" src="https://cloud.githubusercontent.com/assets/4042621/10774975/d318309e-7cd2-11e5-804c-99a2b3533f20.png">



**There are are a lot of ways to fix this.**



**1)** Just target 768px as it seems to be only one affected:

```css
@media (min-width: 768px) {
.search-form.form-inline .input-group > .input-group-btn {
    width: 1%;
 }
}
```

**2)** Use the sibling selector which will get priority:

```css
input#bsg-search-form ~ .input-group-btn {
     width: 1%;
}
```


**3)** Use !important *(hacky solution)*:

```css
.search-form .input-group-btn {
     width: 1% !important;
}
```


----------


On a side note from the search bar width, we also might still need to move the glyphicon search icon down another pixel, at least the way I'm seeing it. This could possibly be retina mac display only though.

```css
.search-form .glyphicon {
    top: 2px;
}
```


----------


Alternatively, we could fix both of these issues using flexbox. While the code here is the longest it is also way cleaner than bootstraps 1% width hack.

```css
.search-form.form-inline .input-group, 
.search-form.form-inline .input-group .input-group-btn {
    display: flex;
}
#bsg-search-form {
    flex: 1;
}
button.search-submit.btn.btn-default {
    display: inline-flex;
    padding: 0 14px;
    justify-content: center;  /* might not be needed */
    align-items: center; /*  might not be needed  */
}
@media (min-width: 768px) {
   .search-form.form-inline > .form-group {
        display: block;
    }
}
```
