### ISSUE TITLE
Remove structural .wrap divs?

### ISSUE THREAD

**Issue by salcode** [salcode/bootstrap-genesis#63]
We are not using the Genesis structural wrap divs, `div.wrap`, within Bootstrap Genesis, however this is a starter theme and I'm wondering if others often use them when building a theme.  In particular, building something like a full-width header or footer comes to mind?

I realize they can be added back easily enough but if they're often used, I'm tempted to keep them in.

@codenameEli, @dustyndoyle, @tbcorr Do you have objections to removing these by default?
No reply will be assumed to be agreement on removing them.

See patch #61

**Comment by bryanwillis** [comment]
Been thinking about this one a lot and how we should go about it...

I think the most important thing here is to decide how we plan on going forward with the layout markup, but more specifically I think we need to make a clear decision as to how Bootstrap fits into Genesis. This is of course just an opinion, but I think this would help get more people get involved and be on the same page moving forward. Obviously we're still in the "figuring things out" phase, but I think the sooner we do that the better!

For instance, the layout option milestones is a good example. You mentioned ![here](https://github.com/salcode/bootstrap-genesis/issues/46#issuecomment-76930758) that you'd like to go forward with the layout options using **php**. In that case I think moving forward we should focus of Bootstrap-Genesis should be making the markup look like Bootstrap's while using Genesis. If we wan't to do it mostly with **css**, then the focus should be integrating Bootstrap, but keeping Genesis as "Genesis" as possible. This probably sounds kind of dumb while reading, but I think it's important if we draw out some guidelines so people now how to get involved with the project.

This all goes along with your particular question here because we could look at the wraps two ways here. We should try to integrate wraps into bootstrap-genesis just how they are with regular genesis. The question is which route to take...

For instance, If we want the markup to be more like Genesis we should change the `.wrap` css to match bootstraps `.container` css using sass/less

Less version (not sure if this is everything):

```less
.wrap {
  .container-fixed();

  @media (min-width: @screen-sm-min) {
    width: @container-sm;
  }
  @media (min-width: @screen-md-min) {
    width: @container-md;
  }
  @media (min-width: @screen-lg-min) {
    width: @container-lg;
  }
}

.wrap {
  > .navbar-header,
  > .navbar-collapse {
    margin-right: -@navbar-padding-horizontal;
    margin-left:  -@navbar-padding-horizontal;

    @media (min-width: @grid-float-breakpoint) {
      margin-right: 0;
      margin-left:  0;
    }
  }
}
```


If we want to go the "bootstrap markup" direction we could turn wraps into containers by actually changing the **wrap** `genesis_attr` to **container**...

```php
<?php
remove_filter( 'genesis_attr_structural-wrap', 'genesis_attributes_structural_wrap' );
add_filter( 'genesis_attr_structural-wrap', 'bootstrap_genesis_attributes_structural_wrap' );
function bootstrap_genesis_attributes_structural_wrap( $attributes ) {
  $attributes['class'] = 'container';
  return $attributes;
}
```

Both of these we could even add container-fluid. Anyway, if we can how we what we want to  integrate bootstrap markup moving forward, I think these questions will be easier for us to figure out. What's your thoughts?
